### ISSUE TITLE
Unable to load the classic pack

### ISSUE THREAD

**Issue by Sunconure11** [KnowYourKnot/ChiselDecor#1]
https://pastebin.com/nT09rCTv

https://pastebin.com/R4R7YUjv

**Comment by KnowYourKnot** [comment]
I was able to recreate this error by placing the classic.zip file into the `config/chiseldecor` directory without un-zipping it. To fix this, make sure you remove the actual blockpack folder from within the ZIP file. This wasn't really clear from the README, so I've edited it to reflect this. Closing this issue, if problems persist then open a new one 👍

**Comment by Sunconure11** [comment]
I tried with and without the zip file.
